"""empty message

Revision ID: 0a085c0cb8e6
Revises: 
Create Date: 2024-06-23 11:44:19.403501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a085c0cb8e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['m_province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['img_id'], ['m_img.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['m_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_bds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('price_from', sa.BigInteger(), nullable=True),
    sa.Column('price_to', sa.BigInteger(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bed_room_quantity', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('sold_flg', sa.Boolean(), nullable=False),
    sa.Column('published_flg', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['m_city.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['m_direction.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['m_province.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['m_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('r_bds_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bds_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bds_id'], ['m_bds.id'], ),
    sa.ForeignKeyConstraint(['img_id'], ['m_img.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('r_user_bds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bds_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bds_id'], ['m_bds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['m_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_user_bds')
    op.drop_table('r_bds_img')
    op.drop_table('m_bds')
    op.drop_table('m_user')
    op.drop_table('m_city')
    op.drop_table('m_type')
    op.drop_table('m_role')
    op.drop_table('m_province')
    op.drop_table('m_img')
    op.drop_table('m_direction')
    # ### end Alembic commands ###
